### ISSUE TITLE
[Bug] Unable to upgrade go.temporal.io/api 1.26->1.27

### ISSUE THREAD

**Issue by nickzelei** [temporalio/api#355]
I'm unable to bump temporal to the latest Go SDK version 1.27 of the `go.temporal.io/api` library.

I upgraded the dependency but am now receiving errors from within the `go.temporal.io/sdk` library (1.25.1)

```
# go.temporal.io/sdk/internal/protocol
/Users/nick/go/pkg/mod/go.temporal.io/sdk@v1.25.1/internal/protocol/util.go:39:40: cannot use msg.Body (variable of type *anypb.Any) as *types.Any value in argument to types.AnyMessageName
# go.temporal.io/sdk/internal/common/metrics
/Users/nick/go/pkg/mod/go.temporal.io/sdk@v1.25.1/internal/common/metrics/grpc.go:120:44: cannot use s (variable of type *"github.com/gogo/status".Status) as *"google.golang.org/grpc/internal/status".Status value in argument to serviceerror.FromStatus
```

Link to PR that I'm trying to upgrade:
https://github.com/nucleuscloud/neosync/pull/1300

Link to specific Github Action
https://github.com/nucleuscloud/neosync/actions/runs/7851544426/job/21428758978?pr=1300

Link to go.mod
https://github.com/nucleuscloud/neosync/blob/dependabot/go_modules/backend/golang-minor-53d5c674f0/backend/go.mod

**Comment by cretz** [comment]
To use the newest Go API version, you have to be on the newest RC of the Go SDK. The Go API library underwent some changes to upgrade to the newest proto library, so you need to make sure you only use the API version that is in the SDK's go.mod. We cannot really update to v2 for larger compatibility and Go versioning reasons.

(closing as question, but feel free to keep commenting or join us on Slack or our forums)

**Comment by nickzelei** [comment]
I see, makes a lot more sense after looking at the RC release notes, which I did not see before. I just went to the homepage and saw the latest release of the sdk was 1.25.1.

Thanks for the clarification!
